### ISSUE TITLE
Adding particle effects

### ISSUE THREAD

**Issue by tritonbui** [tritonbui/Kitchen-Sink#13]
**Is your feature request related to a problem? Please describe.**
No. It is adding in particle effects to improve the aesthetics of the game.

**Describe the solution you'd like**
Having air bubbles around the diver to show that he is breathing, dust particles under divers feet when he/she is walking and having an improved electric field to clearly identify that it is an electric harmful trap.

**Comment by Garmacon** [comment]
Particle effects are done thanks to @tritonbui
