### ISSUE TITLE
Puzzle Mechanics 

### ISSUE THREAD

**Issue by zharabn** [tritonbui/Kitchen-Sink#17]
Extra Puzzle Mechanics, Blocks etc for new, interesting levels for Semester two. 

- Teleporting (Teleporter Block)
- Moving platforms
- Torpedo launch Block
- Brocken Receptable (Trap Block) 
- Water Currents (Like Portal 2 Excursion funnels0

**Comment by Garmacon** [comment]
All Mechanics except the scrapped Brocken Receptacle block have been implemented.
